### PR TITLE
Add initial build support for ppc64le (OpenPOWER) systems

### PR DESCRIPTION
**Pull request by madscientist159**

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Hi, please change destination branch to `develop`, we only merge third-party PR's to develop

**Comment by madscientist159** [comment]
Closing to reopen on develop branch after testing

**Comment by ShockwaveNN** [comment]
Also could you point out an easy way to setup ppc64le server to check those changes?

A think we got similar PR several years ago, but we found one very strange cloud provide which provides such servers but not sure that it's still alive now

Maybe some qemu instance will work?

**Comment by madscientist159** [comment]
I could get you access to a VPS instance to run CI/CD on free of charge, would that work?

You may be thinking of Integricloud, they're a sister company to Raptor and very much alive especially for bare metal POWER server hosting.  Curious what you thought was strange?

**Comment by ShockwaveNN** [comment]
> Integricloud

Yeah it was Integricloud last time, it was rather strange experience compared to standard AWS\DigitalOcean instance, I think we still have an account

I should contact my superiors to decide how much time we can spend on this task anyway

**Pull request closed without merging**
